### ISSUE TITLE
README.md Typos

### ISSUE THREAD

**Issue by jake32321** [Mastercard/pkcs11-tools#20]
I found a couple of typos in README.md. I wanted to make sure I followed the contributing guide as much as possible for this. Since this is such a small change, I am not sure if anything else needs to be included in this.

**Comment by keldonin** [comment]
Thanks for reporting the issues and for submitting a PR. It has been merged to the master branch.

**Comment by jake32321** [comment]
Awesome! Thanks, Eric.
