### ISSUE TITLE
"configure.ac:47: error: possibly undefined macro: AC_MSG_WARN" on CentOS 7.8

### ISSUE THREAD

**Issue by scheblein** [Mastercard/pkcs11-tools#22]
**Describe the bug**
...
autoreconf: running: /usr/bin/autoconf --force
**configure.ac:47: error: possibly undefined macro: AC_MSG_WARN**
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**To Reproduce**
1. git clone https://github.com/Mastercard/pkcs11-tools.git
2. cd pkcs11-tools
3. ./bootstrap.sh

**Expected behavior**
./bootstrap.sh should exit cleanly

**Operating System (please complete the following information):**
 - OS: CentOS Linux
 - Version 7.8.2003 (Core)

**Comment by scheblein** [comment]
[https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error#37980772](https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error#37980772) <- This gets me past the ./bootstrap.sh error, but then dies again now in ./configure, probably due to the fact that i removed the brackets.

...
checking whether yytext is a pointer... no
**./configure: line 4780: syntax error near unexpected token `,{'**
./configure: line 4780: `AX_PROG_FLEX(,{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: GNU flex is required to regenerate lexer. Generated source code is provided, so it should be OK, until you change the lexer source file. Hint: use LEX variable to point to flex on your system." >&5'

**Comment by scheblein** [comment]
interesting - i added **m4_pattern_allow([AC_MSG_WARN])** to the configure.ac file, and i'm still receiving the error in ./configure

checking whether yytext is a pointer... no
**./configure: line 4781: syntax error near unexpected token** `,AC_MSG_WARN'
./configure: line 4781: `AX_PROG_FLEX(,AC_MSG_WARN([GNU flex is required to regenerate lexer. Generated source code is provided, so it should be OK, until you change the lexer source file. Hint: use LEX variable to point to flex on your system.]))'

**Comment by scheblein** [comment]
found the solution! the **autoconf-archive** package needs to be installed (h/t [https://github.com/tpm2-software/tpm2-tss/issues/227#issuecomment-227719745](https://github.com/tpm2-software/tpm2-tss/issues/227#issuecomment-227719745))

**Comment by keldonin** [comment]
@Sheblein, yes autoconf-archive must be installed. Something to add to the documentation.

**Comment by keldonin** [comment]
Documentation updated, to also add `autoconf-archive` to the prerequisites.
