### ISSUE TITLE
Do not store generated files in the git repo

### ISSUE THREAD

**Issue by LudovicRousseau** [Mastercard/pkcs11-tools#6]
**Describe the bug**
Some files are in the git repository but they should not.

**Expected behavior**
The following files should be removed from git:
- compile
- config.guess
- config.rpath
- config.sub
- configure
- depcomp
- install-sh
- Makefile.in
- missing
- ylwrap

The m4/ directory should also be removed unless some specific files are not installed by the aclocal command.

**Operating System (please complete the following information):**
 - OS: any
 - Version any

**Additional context**
files generated by the autotools (automake, autoconf, autoheader, libtool, etc.) should not be in the git repo since they are generated.
You can provide a `bootstrap.sh` script to generated them for example.

**Comment by keldonin** [comment]
Hi @LudovicRousseau , thanks for reporting this.

In theory, yes, you are right, generated source files should not be committed to GIT. However there are cases where it is acceptable, see e.g. [gnulib doc](https://www.gnu.org/savannah-checkouts/gnu/gnulib/manual/gnulib.html#VCS-Issues) for detailed info.

The reason why these are left out there is to allow easy build on platforms where you don't necessarily have autotools deployed (or an old version). On such platforms, you can directly execute `./configure`. This has been the case on e.g. AIX or Solaris.

I could add a `bootstrap.sh`to the project, if that helps on your side for CI/CD purposes. 

I am open to propositions, as long as they allow an easy build process on all platforms.

Regards,

**Comment by LudovicRousseau** [comment]
I understand.
I was not talking about files from Gnulib.

In general your end users should use the `pkcs11-tools-1.0.2.tar.gz` archive generated by `make dist`. This archive contains all the needed files (`./configure`, etc.) with no need to install autotools.

**Comment by keldonin** [comment]
Sorry, for some reason I missed your comment. I will need to rework the project somehow, to remove all the generated source code. 
BTW Feel free to propose a PR!

**Comment by keldonin** [comment]
fixed in commit 2ab2172, tag v1.1.0
